# sausage-store-chart/values.yaml

global:
  imagePullPolicy: Always
  ###vault:
  ###  host: ip
  ###  name: vault
  ###  vaultToken: someToken

frontend:
### В чарте frontend отсутствуют некоторые важные файлы. Поймите какие и опишите их.
  replicas: 1
  containerPort: 80
  image:
    repository: valdmar918/sausage-frontend
    tag: "1.0.0"
  strategy:
    type: Recreate 
  service:
    port: 80
  ingress:
    host: front-vald3mar.2sem.students-projects.ru # Корректный домен будет указан в задании
    path: /
    pathType: Prefix

backend:
  replicas: 1
  containerPort: 8080
  image:
    repository: valdmar918/sausage-backend
    tag: "1.0.0"
  service:
    port: 8080
  env:
    postgresUser: sausage_user
    postgresPasswordSecret: postgresql-secret
    postgresPasswordKey: postgres-password
  vpa:
    enabled: true
    updateMode: "Auto"

backend_report:
### Опишите значения для backend-report
### Приложение должно использовать стратегию Recreate
### Приложение использует переменную PORT - порт, на котором оно запустится и DB - Uri-подключение к mongodb.
### DB положите в Secret, PORT в ConfigMap
### Опишите HPA для backend-report
  replicas: 1
  strategy:
    type: Recreate
  containerPort: 8080
  image:
    repository: valdmar918/sausage-backend-report
    tag: "1.0.0"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

infra:
### Опишите необходимые переменные для развертывания PostgresQL в кластере Kubernetes
  postgresql:
    passwordSecret: postgresql-secret
    passwordKey: postgres-password

  mongodb:
    replicas: 1
    containerPort: 27017
    image:
      repository: mongo
      tag: "4.4"
      pullPolicy: IfNotPresent
    auth:
      username: "admin"
      password: "changeme"
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"