# sausage-store-chart/charts/infra/templates/mongodb-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-mongodb-init
  namespace: {{ .Release.Namespace }}
  annotations:
    # Этот хук заставляет Job запускаться после установки или обновления релиза
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongodb-init-check
          image: mongo:4.4
          command: ['mongo']
          args:
            - "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@mongodb:27017/admin"
            - "--eval"
            - "db.runCommand({ ping: 1 })"
          env:
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
  backoffLimit: 4