apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: infra
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: {{ .Values.mongodb.containerPort }}