apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mongo-root-username: {{ .Values.mongodb.auth.username }}
  mongo-root-password: {{ .Values.mongodb.auth.password }}