apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: infra
spec:
  type: ClusterIP 
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql