# sausage-store-chart/charts/infra/templates/postgresql-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15-alpine 
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "sausage_store"
          - name: POSTGRES_USER
            value: "sausage_user"
          - name: POSTGRES_PASSWORD
            value: {{ .Values.infra.postgresql.password | quote }} 
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data 
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1024Mi"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc