apiVersion: v1
kind: Service
metadata:
  name: backend-report
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/component: backend-report
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.backend-report.containerPort }}
  selector:
    app: backend-report