apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/component: backend-report
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}