apiVersion: v1
kind: Secret
metadata:
  name: backend-report-secret
stringData:
  DB: "mongodb://{{ .Values.infra.mongodb.auth.username }}:{{ .Values.infra.mongodb.auth.password }}@mongodb:27017/sausage-db"