name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_BASE_URL }}/repository/sausage-store-helm-vald3mar
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ secrets.SAUSAGE_STORE_NAMESPACE }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push_to_docker_hub:
      name: Push Docker image to DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to Docker 
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Push Backend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend/
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/sausage-backend:${{ env.IMAGE_TAG }}
            build-args: |
              VERSION=${{ env.IMAGE_TAG }}

        - name: Push Frontend to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./frontend/
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/sausage-frontend:${{ env.IMAGE_TAG }}

        - name: Push Backend-report to DockerHub
          uses: docker/build-push-action@v4
          with:
            context: ./backend-report/
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/sausage-backend-report:${{ env.IMAGE_TAG }}

  add_helm_chart_to_nexus:
      name: Add Helm Chart To Nexus
      runs-on: ubuntu-latest
      needs: build_and_push_to_docker_hub

      steps:
        - uses: actions/checkout@v3

        - name: Set up Helm
          uses: azure/setup-helm@v3
          with:
            version: v3.12.0

        - name: Update Chart Version
          run: |
            # Используем sed для замены строки version: 0.1.0 на version: 0.1.0-<хеш_коммита>
            # Это создаст уникальную версию для каждого запуска пайплайна
            CHART_VERSION="0.1.0-${{ env.IMAGE_TAG }}"
            sed -i "s/^version: .*/version: $CHART_VERSION/" ./sausage-store-chart/Chart.yaml
            echo "New chart version is: $(cat ./sausage-store-chart/Chart.yaml | grep version:)"

        - name: Package chart
          run: |
            rm -rf ./sausage-store-chart/charts/*.tgz
            rm -rf ./sausage-store-chart/Chart.lock
            helm dependency update ./sausage-store-chart/
            
            mkdir -p ./packaged/
            helm package ./sausage-store-chart/ -d ./packaged/

        - name: Push Helm chart to Nexus
          run: |
            CHART_FULL_PATH=$(ls ./packaged/*.tgz)
            CHART_FILE_NAME=$(basename $CHART_FULL_PATH)
            curl -u "$NEXUS_HELM_REPO_USER:$NEXUS_HELM_REPO_PASSWORD" \
            --upload-file "$CHART_FULL_PATH" \
            "$NEXUS_HELM_REPO/$CHART_FILE_NAME"

  deploy_helm_chart_to_kubernetes:
      name: Deploy Helm Chart To Kubernetes
      runs-on: ubuntu-latest
      needs: add_helm_chart_to_nexus

      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Set up Helm
          uses: azure/setup-helm@v3
          with:
            version: v3.12.0
            
        - name: Set Kubeconfig
          run: |
            echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
            export KUBECONFIG=kubeconfig.yaml

        - name: Add Nexus Helm Repository
          run: |
            helm repo add sausage-nexus ${{ env.NEXUS_HELM_REPO }} \
              --username ${{ env.NEXUS_HELM_REPO_USER }} \
              --password ${{ env.NEXUS_HELM_REPO_PASSWORD }}
            helm repo update

        - name: Deploy Helm Chart
          run: |
            export KUBECONFIG=kubeconfig.yaml
            helm repo update
            
            # --- ИЗМЕНЕНО: Добавляем флаг --version и используем уникальный тег ---
            helm upgrade --install sausage-store sausage-nexus/sausage-store \
              --version "0.1.0-${{ env.IMAGE_TAG }}" \
              --namespace ${{ env.SAUSAGE_STORE_NAMESPACE }} \
              --create-namespace \
              --set frontend.fqdn=front-vald3mar.2sem.students-projects.ru \
              --set frontend.image.repository=${{ secrets.DOCKER_USERNAME }}/sausage-frontend \
              --set frontend.image.tag=${{ env.IMAGE_TAG }} \
              --set backend.image.repository=${{ secrets.DOCKER_USERNAME }}/sausage-backend \
              --set backend.image.tag=${{ env.IMAGE_TAG }} \
              --set backend-report.image.repository=${{ secrets.DOCKER_USERNAME }}/sausage-backend-report \
              --set backend-report.image.tag=${{ env.IMAGE_TAG }}